//! `xray mldsa65` parse + remote invoke (IB-L4 Reality).

use feldjaeger_ssh::{RemoteCommand, SshSession};
use tracing::debug;

use super::error::{RemoteCliError, RemoteCliErrorKind, RemoteCliResult};
use super::exec::classify_exec_error;

/// Seed / verify pair from `xray mldsa65`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mldsa65KeyPair {
    /// Server `realitySettings.mldsa65Seed`.
    pub seed: String,
    /// Client verify string (ephemeral UI only).
    pub verify: String,
}

/// Parses stdout from `xray mldsa65`.
pub fn parse_mldsa65_stdout(stdout: &str) -> RemoteCliResult<Mldsa65KeyPair> {
    let mut seed = None;
    let mut verify = None;
    for line in stdout.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("Seed:") {
            seed = Some(rest.trim().to_owned());
        } else if let Some(rest) = line.strip_prefix("Verify:") {
            verify = Some(rest.trim().to_owned());
        }
    }
    let seed = seed.filter(|s| !s.is_empty()).ok_or_else(|| {
        RemoteCliError::new(RemoteCliErrorKind::ParseFailed, "missing Seed".to_owned())
    })?;
    let verify = verify.filter(|s| !s.is_empty()).ok_or_else(|| {
        RemoteCliError::new(RemoteCliErrorKind::ParseFailed, "missing Verify".to_owned())
    })?;
    Ok(Mldsa65KeyPair { seed, verify })
}

/// Runs `xray mldsa65` on the remote host.
pub async fn run_mldsa65<S: SshSession + Sync>(
    session: &S,
    binary_path: &str,
) -> RemoteCliResult<Mldsa65KeyPair> {
    let binary = binary_path.trim();
    if binary.is_empty() {
        return Err(RemoteCliError::new(
            RemoteCliErrorKind::CommandFailed,
            "Xray binary path is empty".to_owned(),
        ));
    }
    let command = RemoteCommand::new(binary, vec!["mldsa65".to_owned()]).map_err(|error| {
        RemoteCliError::new(RemoteCliErrorKind::CommandFailed, error.message().to_owned())
    })?;
    let result = session.exec(&command).await.map_err(classify_exec_error)?;
    if result.exit_code != 0 {
        return Err(RemoteCliError::new(
            RemoteCliErrorKind::NonZeroExit,
            format!("exit code {}", result.exit_code),
        ));
    }
    let stdout = String::from_utf8_lossy(&result.stdout);
    debug!(stdout_len = stdout.len(), "parsed remote xray mldsa65 stdout");
    parse_mldsa65_stdout(&stdout)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `xray mldsa65 -i <SEED>` stdout, generated by the official binary (deterministic per seed).
    const FIXTURE: &str = include_str!("fixtures/mldsa65.stdout.txt");
    const SEED: &str = "P9RyqiJHEImAn03AhiVio4mNzxECpqmSgcpqyR5DhAs";

    #[test]
    fn parses_fixture() {
        let pair = parse_mldsa65_stdout(FIXTURE).unwrap();
        assert_eq!(pair.seed, SEED);
        assert!(pair.verify.len() > 100);
    }

    /// The parser keeps up with the current CLI output, and the fixture is still what the core
    /// prints for the same seed (skipped without a local Xray).
    #[test]
    fn parses_local_xray_output() {
        let Some(stdout) = crate::xray::local_xray::local_xray_stdout(&["mldsa65", "-i", SEED]) else {
            return;
        };
        assert_eq!(parse_mldsa65_stdout(&stdout).unwrap(), parse_mldsa65_stdout(FIXTURE).unwrap());
    }
}
