//! Xray configuration and lifecycle management.
//!
//! Uses [`crate::init::InitSystemManager`] for service control and
//! [`crate::remote::RemoteAdmin`] for configuration I/O.
//! Does not depend on SSH library APIs directly.

mod cert_pin;
pub mod config;
mod discovery;
mod geodata;
mod installation;
mod installer;
#[cfg(test)]
pub(crate) mod local_xray;
pub mod logs;
mod manager;
pub mod remote_cli;
pub mod secret;
pub mod share_uri;
mod validator;
pub mod warp;
mod x25519_local;

pub use config::{
    AddConfdirFileRequest, AddInboundClientRequest, AddInboundRequest, AddOutboundRequest,
    AddOutboundShellRequest,
    AddUserRequest, ApiSettings, DnsHostEntry, DnsServerEntry, DnsSettings, QueryStrategy,
    FakeDnsPoolEntry, FakeDnsSettings, UpdateFakeDnsSettingsRequest,
    KNOWN_API_SERVICES, UpdateApiSettingsRequest, UpdateDnsSettingsRequest,
    BLACKHOLE_RESPONSE_TYPES, DNS_REWRITE_NETWORKS, DNS_RULE_ACTIONS, DnsRuleDraft,
    FREEDOM_DEFAULT_BLOCK_DELAY, FREEDOM_FINAL_RULE_ACTIONS, FREEDOM_FINAL_RULE_NETWORKS,
    FREEDOM_NOISE_TYPES, FREEDOM_PROXY_PROTOCOL_VERSIONS, FragmentDraft, FreedomFinalRuleDraft,
    FreedomSettingsDraft, LegacyDomainStrategyMigration, LoopbackRouting, LoopbackSettingsDraft, NoiseDraft, loopback_routing,
    OutboundGeneral, OutboundRef, OutboundSettingsDraft, ProxySettingsMigration, UpdateOutboundShellRequest,
    MUX_CONCURRENCY_EFFECTIVE_MAX, MUX_XUDP_CONCURRENCY_DOCUMENTED_MAX, MUX_XUDP_PROXY_UDP443_VALUES,
    OutboundMux, parse_outbound_mux, validate_outbound_mux,
    DialerProxyProblem, GrpcClientSettings, HYSTERIA_TRANSPORT_VERSION, HttpUpgradeClientSettings,
    HysteriaClientSettings, OutboundSecurityDraft, OutboundStreamDraft, OutboundTransport,
    REALITY_REFUSED_FINGERPRINTS, RawClientSettings, RealityClientDraft, RealityPublicKeyField,
    TLS_KNOWN_FINGERPRINTS, TlsClientDraft, WsClientSettings, apply_outbound_stream, dialer_proxy_problem,
    outbound_protocol_has_transport, outbound_protocol_uses_sockopt, outbound_transports_for_protocol, parse_outbound_stream,
    validate_outbound_stream,
    add_outbound_shell, apply_outbound_general, apply_outbound_settings, is_shell_editable_protocol,
    outbound_shell_blocker, parse_outbound_general, parse_outbound_settings, update_outbound_shell,
    SHELL_EDITABLE_PROTOCOLS,
    validate_send_through,
    ALPN_PRESETS, BurstObservatorySummary, BurstPingConfigSummary, CERT_USAGE_PRESETS,
    CompatibilityGateId, CompatibilityWarning, CompatibilityWarningId, WarningSeverity, inbound_warnings,
    outbound_warnings, with_warning_suffix, CORE_FEATURES, CoreFeature, XrayCoreVersion, ConfigError, ConfigErrorKind, ConfigModifyError, ConfigModifyErrorKind,
    ConfigModifyResult, ConfigParseOutcome, CURVE_PRESETS, DeleteInboundClientRequest,
    DeleteInboundRequest, DeleteOutboundRequest, DeleteUserRequest, DnsHostSummary,
    DuplicateInboundRequest, DuplicateOutboundRequest, DnsServerSummary, DnsSummary,
    EditableXrayConfig, FINGERPRINT_PRESETS,
    FakeDnsAddressFamily, FakeDnsPoolSummary, FakeDnsSummary, FallbackDest, FallbackDestKind,
    FallbackObject, FinalMaskLayerDraft, InboundClientProtocol, InboundClientSummary,
    InboundGeneral, InboundLocation,
    InboundProtocolDraft, InboundRef, InboundSecurityDraft, InboundSecurityMode, InboundStreamDraft,
    InboundSummary, JsonDiffEntry, JsonDiffKind, KNOWN_DEST_OVERRIDE, KNOWN_SECTION_NAMES,
    KCP_CWND_MULTIPLIER_MIN, KCP_DEFAULT_CWND_MULTIPLIER, KCP_DEFAULT_DOWNLINK,
    KCP_DEFAULT_MAX_SENDING_WINDOW, KCP_DEFAULT_MTU, KCP_DEFAULT_TTI, KCP_IGNORED_FIELDS,
    KCP_LEGACY_OBFUSCATION_FIELDS,
    KCP_DEFAULT_UPLINK, KCP_MTU_MIN, KCP_TTI_MAX,
    KCP_TTI_MIN, KcpStreamSettings, LogLevel, LogOutput, LogSettings, MaskAddress,
    ADDRESS_PORT_STRATEGIES, DOMAIN_STRATEGIES, HappyEyeballsDraft, INBOUND_ONLY_SOCKOPT_FIELDS,
    OUTBOUND_ONLY_SOCKOPT_FIELDS, QuicParamsDraft, SockoptDraft, StreamDirection, sockopt_field_applies,
    QuicTransport, XHTTP3_CONGESTION_MODES, alpn_selects_http3, quic_transport_of,
    validate_quic_params_for_transport, validate_stream_quic_params,
    DIAL_HANDLING_UDP_FINALMASK_TYPES, LEGACY_UDP_HOP_MODE, LegacyUdpHopMigration,
    QUIC_PARAMS_LEGACY_UDP_HOP_KEY, migrate_legacy_udp_hop, udphop_layer_from_legacy_udp_hop,
    INBOUND_ONLY_QUIC_PARAMS_FIELDS, OUTBOUND_ONLY_QUIC_PARAMS_FIELDS, QUIC_BBR_PROFILES,
    QUIC_CONGESTION_MODES, QUIC_KEEP_ALIVE_PERIOD_RANGE, QUIC_MAX_IDLE_TIMEOUT_RANGE,
    QUIC_MIN_BRUTAL_BYTES_PER_SEC, QUIC_MIN_INCOMING_STREAMS, QUIC_MIN_RECEIVE_WINDOW,
    parse_quic_params, quic_bandwidth_bytes_per_sec, quic_params_field_applies, validate_quic_params,
    CLIENT_ONLY_UDP_FINALMASK_TYPES, FinalMaskChain, UDPHOP_DEFAULT_INTERVAL_SECS,
    UDPHOP_LEGACY_SOCKOPT_KEY, UDPHOP_MIN_INTERVAL_SECS, UdpHopModes, finalmask_layer_type_applies, finalmask_tcp_layer_faces_probes,
    parse_realm_url, parse_udphop_mode, validate_udphop_settings, REALM_DEFAULT_PORT_MAP_LIFETIME_SECS,
    REALM_DEFAULT_PORT_MAP_TIMEOUT_SECS, REALM_IP_MODES, RealmPortMapping, RealmScheme, RealmUrl,
    realm_ip_mode_is_known, validate_realm_settings,
    validate_finalmask_layer, MKCP_LEGACY_HEADERS, HEADER_CUSTOM_UDP_MODES,
    MKCP_LEGACY_DEFAULT_DNS_DOMAIN, MkcpLegacyMode, MkcpLegacySettings, mkcp_legacy_settings_to_value,
    parse_mkcp_legacy_settings, validate_mkcp_legacy_settings,
    XMC_LEGACY_DEFAULT_USERNAME, XMC_MAX_PASSWORD_BYTES, XmcProfile,
    XmcSettings, migrate_legacy_xmc_usernames, parse_xmc_settings, xmc_settings_to_value,
    xmc_username_is_valid,
    HeaderCustomItem, HeaderCustomItemKind, HeaderCustomSequences, HeaderCustomTcpGroup,
    HeaderCustomTcpSettings, header_custom_tcp_settings_to_value, parse_header_custom_tcp_settings,
    HEADER_CUSTOM_UDP_DEFAULT_MODE, HeaderCustomItems, HeaderCustomUdpGroup, HeaderCustomUdpSettings,
    header_custom_udp_settings_to_value, parse_header_custom_udp_settings,
    escape_packet_text, unescape_packet_text,
    FRAGMENT_PACKETS_TLSHELLO, FragmentPackets, fragment_packets_mode, NoiseItemPayload, SALAMANDER_MIN_PASSWORD_BYTES,
    SUDOKU_ASCII_MODES, SUDOKU_MAX_PADDING, validate_sudoku_custom_table, validate_sudoku_settings,
    NOISE_EXP_KIND,
    XDNS_DEFAULT_LABEL_LIMIT, XDNS_DEFAULT_LEN_LIMIT, XDNS_RECORD_TYPES, XDNS_RESOLVER_KINDS,
    XdnsDomain, XdnsResolver, migrate_legacy_xdns_settings, xdns_has_legacy_fields,
    xdns_record_type_name,
    TCP_CONGESTION_PRESETS, TPROXY_MODES, TcpFastOpenDraft,
    XHTTP_DOWNLOAD_SECURITIES, XHTTP_MODES, XHTTP_MODE_DEFAULT, XHTTP_PADDING_METHODS,
    XHTTP_PATH_DEFAULT, XHTTP_PLACEMENTS, XHTTP_SESSION_ID_TABLES, XHTTP_UPLINK_METHODS,
    XhttpCoreSettings, XhttpDownloadDraft, XhttpRange, XhttpStreamSettings, XmuxDraft,
    ModifyConfigOutcome, ModifyUserOutcome, ObservatorySummary, OutboundKind, OutboundLocation,
    OutboundSummary, PolicySummary, RealityDestinationKey, RealityLimitFallbackDraft,
    RealitySettingsDraft,
    RemoveConfdirFileRequest, RemoveOutboundRequest, RenameOutboundOutcome, RenameOutboundTagRequest,
    ReplaceInboundRawJsonRequest, ReplaceOutboundRawJsonRequest, ReplaceOutboundRequest,
    ReverseSniffingDraft, ReverseTagDraft, parse_reverse, reverse_to_value, validate_reverse,
    RoutingRuleSummary, RoutingSummary,
    SUPPORTED_USER_PROTOCOL, SecretFieldDraft, SniffingSettings, SniffingWriteOutcome,
    SourcedSection, StreamMethod, StreamMethodKey, SupportedUserInbound, SystemPolicySummary,
    TCP_FINALMASK_TYPES, TLS_VERSION_PRESETS, TUN_WFP_BLOCK_LEAK_VALUES, TUNNEL_NETWORKS,
    UDP_FINALMASK_TYPES, validate_tun_settings,
    FragmentMaskSettings, NoiseMaskItem, NoiseMaskSettings, RealmSettings, SalamanderSettings,
    SudokuSettings, UdpHopSettings, XdnsSettings, XicmpSettings, fragment_mask_settings_to_value,
    noise_mask_settings_to_value, parse_fragment_mask_settings, parse_noise_mask_settings,
    parse_realm_settings, parse_salamander_settings, parse_sudoku_settings, parse_udphop_settings,
    parse_xdns_settings, parse_xicmp_settings, realm_settings_to_value,
    salamander_settings_to_value, sudoku_settings_to_value, udphop_settings_to_value,
    xdns_settings_to_value, xicmp_settings_to_value, PacketValue, PortListValue, RangeValue,
    parse_range_values, range_values_from_lines, range_values_to_lines,
    CertificateDraft, TlsSettingsDraft, TrojanClientSummary,
    HysteriaClientSummary, UpdateInboundClientRequest, UpdateInboundGeneralRequest,
    UpdateInboundShellRequest, UpdateInboundSniffingRequest, UpdateLogSettingsRequest,
    UpdateUserRequest, UserPolicySummary, UserSummary, VlessClientSummary, XrayConfig,
    XrayConfigParser, XrayConfigSections, add_confdir_file, add_inbound, add_inbound_client,
    add_outbound, add_user, compose_inbound_shell, build_add_inbound_value,
    apply_fallbacks, apply_inbound_general, apply_inbound_protocol, apply_inbound_security,
    apply_inbound_sniffing, apply_inbound_stream, apply_tunnel_stream, allowed_security_modes, allowed_stream_methods,
    api_settings_change_summary, api_settings_from_section, api_settings_to_new_value,
    apply_api_settings_to_value, update_api_settings, validate_api_settings,
    validate_api_settings_for_config,
    apply_dns_settings_to_value, dns_settings_change_summary, dns_settings_from_section,
    dns_settings_to_new_value, update_dns_settings, validate_dns_settings,
    apply_fakedns_settings_to_value, fakedns_settings_change_summary, fakedns_settings_from_section,
    fakedns_settings_to_new_value, update_fakedns_settings, validate_fakedns_settings,
    apply_routing_settings_to_value, routing_settings_change_summary, routing_settings_from_section,
    routing_settings_to_new_value, update_routing_settings, validate_routing_settings,
    BalancerEntry, BalancerStrategyType, CostEntry, DomainStrategy, NetworkKind, RoutingRuleEntry,
    RoutingSettings, StrategyEntry, StrategySettingsEntry, UpdateRoutingSettingsRequest, WebhookEntry,
    apply_policy_settings_to_value, policy_settings_change_summary, policy_settings_from_section,
    policy_settings_to_new_value, update_policy_settings, validate_policy_settings,
    PolicyLevelEntry, PolicySettings, SystemPolicyEntry, UpdatePolicySettingsRequest,
    apply_observatory_settings_to_value, observatory_settings_change_summary,
    observatory_settings_from_section, observatory_settings_to_new_value,
    update_observatory_settings, validate_observatory_settings,
    ObservatorySettings, UpdateObservatorySettingsRequest,
    apply_burst_observatory_settings_to_value, burst_observatory_settings_change_summary,
    burst_observatory_settings_from_section, burst_observatory_settings_to_new_value,
    update_burst_observatory_settings, validate_burst_observatory_settings,
    BurstObservatorySettings, BurstPingConfigEntry, UpdateBurstObservatorySettingsRequest,
    stats_settings_change_summary, stats_settings_from_section, stats_settings_to_value,
    update_stats_settings, validate_stats_settings,
    StatsSettings, UpdateStatsSettingsRequest,
    apply_metrics_settings_to_value, metrics_settings_change_summary,
    metrics_settings_from_section, metrics_settings_to_new_value, update_metrics_settings,
    validate_metrics_settings, MetricsSettings, UpdateMetricsSettingsRequest,
    apply_env_settings_to_value, env_settings_change_summary, env_settings_from_section,
    env_settings_to_new_value, update_env_settings, validate_env_settings,
    EnvSettings, EnvVarEntry, KNOWN_ENV_VARS, UpdateEnvSettingsRequest,
    apply_version_settings_to_value, version_settings_change_summary,
    version_settings_from_section, version_settings_to_new_value, update_version_settings,
    validate_version_settings, VersionSettings, UpdateVersionSettingsRequest,
    apply_geodata_settings_to_value, geodata_settings_change_summary,
    geodata_settings_from_section, geodata_settings_to_new_value, update_geodata_settings,
    validate_geodata_settings, GeodataSettings, GeodataAssetEntry, UpdateGeodataSettingsRequest,
    apply_log_settings_to_value, burst_observatory_summary, check_inbound_compatibility,
    check_outbound_compatibility, first_failing_outbound_gate,
    clients_for_inbound, coerce_display_stream_method, coerce_security_mode_for_transport,
    cmp_policy_level, delete_inbound, delete_inbound_client, delete_outbound, delete_user,
    dns_summary, duplicate_inbound, duplicate_outbound, effective_security, extract_inbound_clients,
    extract_vless_clients, fakedns_summary, fallbacks_compatible_on_inbound,
    fallbacks_transport_compatible, first_failing_gate, format_tag_reference_block,
    g10_hysteria_requires_tls, g11_shadowsocks_tcp_only, g9_hysteria_protocol_transport_ok,
    finalmask_layers_to_value, generate_client_auth, generate_client_uuid,
    ClientFinalMask, ServerFinalMaskImport, client_finalmask, server_finalmask_from_client,
    hy2_share_obfs, inbound_fingerprint,
    inbound_has_vision_flow,
    inbound_summaries, inbound_tag_references, is_custom_mask_format, join_ws_path_and_ed,
    log_settings_change_summary, log_settings_from_section, log_settings_to_new_value,
    matrix_transport, normalized_method, observatory_summary, outbound_summaries,
    outbound_tag_references, parse_fallbacks, parse_file_roots, parse_finalmask_layers,
    parse_inbound_general,
    parse_inbound_protocol, parse_inbound_security, parse_inbound_stream, parse_sniffing_settings,
    parse_sockopt, sockopt_to_value,
    policy_summary, port_hop_syntax, port_is_shell_editable, raw_port_display,
    reconcile_inbound_fallbacks, redacted_json_diff, redacted_json_diff_bytes,
    redacted_json_diff_lines,
    remove_confdir_file, remove_outbound, rename_outbound_tag, replace_inbound_raw_json,
    replace_outbound, replace_outbound_raw_json, routing_summary,
    routing_wiring_warnings, first_hop_port,
    selectable_stream_methods, sniffing_is_absent_defaults, split_ws_path_and_ed,
    stats_wiring_warnings, supported_user_inbounds, supported_vless_user_inbounds,
    transport_security_allowed,
    trojan_reality_stream_settings, update_inbound_client, update_inbound_general,
    update_inbound_shell, update_inbound_sniffing, update_log_settings, update_user,
    validate_custom_mask_format, validate_fallbacks, validate_finalmask_layers,
    validate_kcp_settings, validate_listen_address, validate_sockopt,
    validate_log_settings, validate_port_map_target, validate_xhttp_settings,
    vision_active_from_inbound, vless_clients_for_inbound, xhttp_extra_json,
};
pub use remote_cli::{
    ConfigTestTarget, DebugVars, HealthPingMeasurement, MetricsMemStats, Mldsa65KeyPair,
    ObservatoryOutboundStatus, RemoteCliError, RemoteCliErrorKind, RemoteCliResult, StatCounter,
    SysStats, VlessEncAuthKind, VlessEncOutput, VlessEncPair, X25519KeyPair,
    parse_debug_vars_stdout, parse_mldsa65_stdout, parse_stats_query_stdout,
    parse_stats_sys_stdout, parse_vlessenc_stdout, parse_x25519_stdout, run_config_test,
    run_metrics_scrape, run_mldsa65, run_vlessenc, run_x25519, run_xray_api,
};
pub use discovery::{DiscoveryResult, XrayDiscoveryService};
pub use geodata::{
    GeoDataDatabaseSummary, GeoDataError, GeoDataErrorKind, GeoDataManager, GeoDataResolveHints,
    GeoDataResult, GeoDataSummary, parse_asset_dir_from_environment,
};
pub use installation::{
    ConfigSource, DiscoveryErrorKind, DiscoveryState, DiscoveryWarning, InitSystemKind,
    XrayInstallation,
};
pub use installer::{
    AvailableVersions, InstallChannel, InstallerError, InstallerErrorKind, InstallerResult,
    XrayInstaller, normalize_version_tag, parse_beta_tag, parse_latest_tag, version_gt,
};
pub use logs::{
    XrayLogAvailability, XrayLogConfigView, XrayLogDestination, XrayLogEntry, XrayLogError,
    XrayLogErrorKind, XrayLogLineLimit, XrayLogResult, XrayLogSearch, XrayLogService,
    XrayLogSourceKind, XrayLogSourceSummary, XrayLogStreamEvent, log_config_view,
};
pub use cert_pin::cert_pin_sha256;
pub use manager::XrayManager;
pub use secret::SecretString;
pub use share_uri::{
    ParsedShareUri, ShareProtocol, ShareSecurity, ShareTransport, ShareUriError, ShareUriRequest,
    build_share_uri, parse_share_uri, pct_decode, pct_encode,
};
pub use validator::{ConfigValidator, DefaultConfigValidator};
pub use x25519_local::public_key_from_private_key;
pub use warp::{
    outbound_value_with_tag, WarpAdoptionOutcome, WarpConnectivityResult, WarpCredentials,
    WarpError, WarpErrorKind, WarpIntegrationState, WarpManager, WarpOutboundClassification,
    WarpOwnershipRecord, WarpProposedChange, WarpRemovalPlan, WarpResult, WarpSummary,
    DEFAULT_WARP_OUTBOUND_TAG,
};
