//! Hysteria `finalmask.udp` against the real core (Roadmap §2.6 stage 4.1).
//!
//! [`hy2_share_obfs`] decides what a hy2 share link carries of a server's `finalmask.udp` chain.
//! Its rules (skip `noise`, refuse Gecko and every other layer) are claims about Xray-core, so
//! they are checked here end to end: a Hysteria server with the chain, a Hysteria client with the
//! chain the link implies (a plain salamander from `obfs`, or nothing — what the hy2 import
//! builds), a `tunnel` inbound in front of the client and a TCP echo server behind the server.
//! - `Ok(obfs)` — the client must get the echo back;
//! - `Err(_)` — the link Feldjäger used to build (the first salamander's password as plain
//!   `obfs`, Roadmap §3:121) must **not** work, i.e. refusing it was right.
//!
//! Two controls keep a broken setup from passing as "refused correctly": identical Gecko chains
//! on both sides connect, and a salamander server without a client mask does not.
//!
//! Runs only with a local Xray ([`crate::xray::local_xray`]); TLS material comes from that binary
//! (`xray tls cert` / `xray tls hash`), never from Feldjäger.

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream, UdpSocket};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::time::{Duration, Instant};

use serde_json::{Value, json};

use crate::xray::local_xray::local_xray_bin;
use super::{FinalMaskChain, client_finalmask, hy2_share_obfs, parse_finalmask_layers};

/// How long the client's `tunnel` inbound may take to start listening.
const STARTUP_TIMEOUT: Duration = Duration::from_secs(5);
/// How long to wait for the echo once the request is sent; a mask mismatch shows up as silence.
const ECHO_TIMEOUT: Duration = Duration::from_secs(4);
const PAYLOAD: &[u8] = b"feldjaeger-hy2";

/// TLS material for the Hysteria server, generated by the core itself.
struct Tls {
    certificate: Value,
    key: Value,
    /// `xray tls hash` of the certificate — the client's `pinnedPeerCertSha256`.
    pin: String,
}

/// An Xray process, killed when the case ends (also on panic).
struct Peer(Child);

impl Drop for Peer {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}

fn run_xray(xray: &Path, args: &[&str]) -> String {
    let output = Command::new(xray)
        .args(args)
        .output()
        .unwrap_or_else(|error| panic!("cannot run {}: {error}", xray.display()));
    assert!(output.status.success(), "xray {args:?} failed: {}", String::from_utf8_lossy(&output.stderr));
    String::from_utf8_lossy(&output.stdout).into_owned()
}

/// A self-signed certificate from `xray tls cert`, pinned by `xray tls hash`. Feldjäger's own
/// `cert_pin_sha256` (the hy2 `pinSHA256`) must agree with the core's hash.
fn generate_tls(xray: &Path, dir: &Path) -> Tls {
    let cert: Value = serde_json::from_str(&run_xray(xray, &["tls", "cert", "-domain=hy.test"]))
        .expect("`xray tls cert` prints JSON");
    let pem = cert["certificate"]
        .as_array()
        .expect("certificate lines")
        .iter()
        .map(|line| line.as_str().expect("PEM line"))
        .collect::<Vec<_>>()
        .join("\n");
    let pem_path = dir.join("hy.crt");
    std::fs::write(&pem_path, format!("{pem}\n")).expect("write certificate");
    let hash = run_xray(xray, &["tls", "hash", "--cert", pem_path.to_str().expect("UTF-8 temp path")]);
    let pin = hash
        .lines()
        .find_map(|line| line.trim().strip_prefix("Leaf SHA256:"))
        .map(|hex| hex.trim().to_owned())
        .unwrap_or_else(|| panic!("unexpected `xray tls hash` output: {hash}"));
    assert_eq!(
        crate::xray::cert_pin_sha256(pem.as_bytes()).expect("Feldjäger pin"),
        pin,
        "cert_pin_sha256 disagrees with `xray tls hash`"
    );
    Tls { certificate: cert["certificate"].clone(), key: cert["key"].clone(), pin }
}

/// A TCP echo server on a free loopback port, for the lifetime of the test process.
fn spawn_echo_server() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").expect("echo listener");
    let port = listener.local_addr().expect("echo address").port();
    std::thread::spawn(move || {
        for mut stream in listener.incoming().flatten() {
            std::thread::spawn(move || {
                let mut buffer = [0u8; 4096];
                while let Ok(read @ 1..) = stream.read(&mut buffer) {
                    if stream.write_all(&buffer[..read]).is_err() {
                        break;
                    }
                }
            });
        }
    });
    port
}

fn free_udp_port() -> u16 {
    UdpSocket::bind("127.0.0.1:0").and_then(|socket| socket.local_addr()).expect("free UDP port").port()
}

fn free_tcp_port() -> u16 {
    TcpListener::bind("127.0.0.1:0").and_then(|listener| listener.local_addr()).expect("free TCP port").port()
}

fn server_config(port: u16, tls: &Tls, udp: &Value) -> Value {
    json!({
        "log": {"loglevel": "warning", "access": "none"},
        "inbounds": [{
            "listen": "127.0.0.1",
            "port": port,
            "protocol": "hysteria",
            "settings": {"version": 2, "clients": [{"auth": "interop-secret"}]},
            "streamSettings": {
                "network": "hysteria",
                "security": "tls",
                "tlsSettings": {"certificates": [{"certificate": tls.certificate, "key": tls.key}]},
                "hysteriaSettings": {"version": 2},
                "finalmask": {"udp": udp}
            }
        }],
        // Freedom refuses private targets by default; the echo server lives on loopback.
        "outbounds": [{"protocol": "freedom", "settings": {"finalRules": [{"action": "allow", "ip": ["127.0.0.1"]}]}}]
    })
}

fn client_config(tunnel_port: u16, echo_port: u16, server_port: u16, tls: &Tls, udp: &Value) -> Value {
    json!({
        "log": {"loglevel": "warning", "access": "none"},
        "inbounds": [{
            "listen": "127.0.0.1",
            "port": tunnel_port,
            "protocol": "tunnel",
            "settings": {"address": "127.0.0.1", "port": echo_port, "network": "tcp"}
        }],
        "outbounds": [{
            "protocol": "hysteria",
            "settings": {"version": 2, "address": "127.0.0.1", "port": server_port},
            "streamSettings": {
                "network": "hysteria",
                "security": "tls",
                "tlsSettings": {"serverName": "hy.test", "pinnedPeerCertSha256": tls.pin},
                "hysteriaSettings": {"version": 2, "auth": "interop-secret"},
                "finalmask": {"udp": udp}
            }
        }]
    })
}

fn start(xray: &Path, config_path: &Path, config: &Value) -> Peer {
    std::fs::write(config_path, serde_json::to_string_pretty(config).expect("serialize config")).expect("write config");
    let child = Command::new(xray)
        .arg("run")
        .arg("-c")
        .arg(config_path)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap_or_else(|error| panic!("cannot start {}: {error}", xray.display()));
    Peer(child)
}

/// Fails the case when a peer exited — a config the core refused must not read as "no echo".
fn assert_running(peer: &mut Peer, role: &str, label: &str) {
    if let Ok(Some(status)) = peer.0.try_wait() {
        let mut log = String::new();
        if let Some(stdout) = peer.0.stdout.as_mut() {
            let _ = stdout.read_to_string(&mut log);
        }
        panic!("{label}: the {role} exited ({status}):\n{log}");
    }
}

/// Starts a server with `server_udp` and a client with `client_udp`; true when a payload sent
/// through the client comes back from the echo server.
fn echoes(xray: &Path, dir: &Path, tls: &Tls, echo_port: u16, label: &str, server_udp: &Value, client_udp: &Value) -> bool {
    let (server_port, tunnel_port) = (free_udp_port(), free_tcp_port());
    let server = server_config(server_port, tls, server_udp);
    let client = client_config(tunnel_port, echo_port, server_port, tls, client_udp);
    run_echo(xray, dir, label, &server, &client, tunnel_port)
}

/// Starts both peers; true when a payload sent into the client's `tunnel` inbound on
/// `tunnel_port` comes back from the echo server.
fn run_echo(xray: &Path, dir: &Path, label: &str, server_config: &Value, client_config: &Value, tunnel_port: u16) -> bool {
    let slug: String = label.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '-' }).collect();
    let mut server = start(xray, &dir.join(format!("{slug}-server.json")), server_config);
    let mut client = start(xray, &dir.join(format!("{slug}-client.json")), client_config);

    let started = Instant::now();
    let mut stream = loop {
        match TcpStream::connect(("127.0.0.1", tunnel_port)) {
            Ok(stream) => break stream,
            Err(_) if started.elapsed() < STARTUP_TIMEOUT => std::thread::sleep(Duration::from_millis(100)),
            Err(error) => {
                assert_running(&mut client, "client", label);
                panic!("{label}: the client's tunnel inbound never came up: {error}");
            }
        }
    };
    stream.set_read_timeout(Some(ECHO_TIMEOUT)).expect("read timeout");
    stream.write_all(PAYLOAD).expect("send payload");
    let mut reply = vec![0u8; PAYLOAD.len()];
    let echoed = stream.read_exact(&mut reply).is_ok() && reply == PAYLOAD;

    assert_running(&mut server, "server", label);
    assert_running(&mut client, "client", label);
    echoed
}

fn salamander(extra: Value) -> Value {
    let mut settings = json!({"password": "interop-obfs"});
    if let (Some(settings), Some(extra)) = (settings.as_object_mut(), extra.as_object()) {
        settings.extend(extra.clone());
    }
    json!({"type": "salamander", "settings": settings})
}

fn noise() -> Value {
    json!({"type": "noise", "settings": {"noise": [{"rand": "10-20", "delay": "0"}]}})
}

/// The client chain a hy2 link implies: `obfs=salamander&obfs-password=…` imports as one plain
/// salamander layer (`inbounds.rs` hy2 import), no `obfs` as no layer.
fn chain_from_link(obfs: Option<&str>) -> Value {
    json!(obfs.map(|password| vec![json!({"type": "salamander", "settings": {"password": password}})]).unwrap_or_default())
}

/// What the pre-4.1 detector put into the link: the first salamander's password, any mode.
fn pre_4_1_link_chain(server_udp: &Value) -> Value {
    let password = server_udp.as_array().into_iter().flatten().find_map(|layer| {
        (layer["type"] == "salamander").then(|| layer["settings"]["password"].as_str()).flatten()
    });
    chain_from_link(password)
}

#[test]
fn hy2_share_obfs_matches_the_core() {
    let Some(xray) = local_xray_bin() else {
        eprintln!("no local Xray (XRAY_BIN / xray-bin) — skipping the Hysteria FinalMask interop check");
        return;
    };
    let dir: PathBuf = std::env::temp_dir().join(format!("feldjaeger-hy2-interop-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("interop temp dir");
    let tls = generate_tls(&xray, &dir);
    let echo_port = spawn_echo_server();
    let gecko = salamander(json!({"packetSize": "512-1200"}));

    let server_chains: Vec<(&str, Value)> = vec![
        ("no masks", json!([])),
        ("salamander", json!([salamander(json!({}))])),
        ("noise then salamander", json!([noise(), salamander(json!({}))])),
        ("salamander then noise", json!([salamander(json!({})), noise()])),
        ("Gecko salamander", json!([gecko.clone()])),
        ("sudoku then salamander", json!([{"type": "sudoku", "settings": {"password": "interop-sudoku"}}, salamander(json!({}))])),
    ];
    // (label, server chain, client chain, should echo)
    let mut runs: Vec<(String, Value, Value, bool)> = server_chains
        .into_iter()
        .map(|(label, server_udp)| {
            let layers = parse_finalmask_layers(server_udp.as_array().expect("chain")).expect("typed layers");
            match hy2_share_obfs(&layers) {
                Ok(obfs) => (format!("{label}: link"), server_udp, chain_from_link(obfs.as_deref()), true),
                Err(_) => {
                    let client = pre_4_1_link_chain(&server_udp);
                    (format!("{label}: refused link"), server_udp, client, false)
                }
            }
        })
        .collect();
    runs.push(("control: Gecko on both sides".to_owned(), json!([gecko.clone()]), json!([gecko]), true));
    runs.push(("control: salamander, client unmasked".to_owned(), json!([salamander(json!({}))]), json!([]), false));

    // Each run has its own ports, so they go in parallel: a refused case costs ECHO_TIMEOUT.
    let failures: Vec<String> = std::thread::scope(|scope| {
        let handles: Vec<_> = runs
            .iter()
            .map(|(label, server_udp, client_udp, expected)| {
                let (xray, dir, tls) = (&xray, &dir, &tls);
                scope.spawn(move || {
                    let echoed = echoes(xray, dir, tls, echo_port, label, server_udp, client_udp);
                    (echoed != *expected).then(|| {
                        format!(
                            "{label}: expected {}, got {}\n  server udp: {server_udp}\n  client udp: {client_udp}",
                            if *expected { "an echo" } else { "no echo" },
                            if echoed { "an echo" } else { "none" },
                        )
                    })
                })
            })
            .collect();
        handles.into_iter().filter_map(|handle| handle.join().expect("interop run panicked")).collect()
    });
    let _ = std::fs::remove_dir_all(&dir);
    assert!(failures.is_empty(), "hy2 obfs mapping disagrees with Xray-core:\n{}", failures.join("\n"));
}

const VLESS_ID: &str = "4a0b6a2c-7f61-4c2b-9d43-3c1c2f5e8a10";

/// A VLESS inbound without security on `network`, with `finalmask` as the server's chains.
fn vless_server_config(port: u16, network: &str, finalmask: &Value) -> Value {
    json!({
        "log": {"loglevel": "warning", "access": "none"},
        "inbounds": [{
            "listen": "127.0.0.1",
            "port": port,
            "protocol": "vless",
            "settings": {"clients": [{"id": VLESS_ID}], "decryption": "none"},
            "streamSettings": {"network": network, "security": "none", "finalmask": finalmask}
        }],
        "outbounds": [{"protocol": "freedom", "settings": {"finalRules": [{"action": "allow", "ip": ["127.0.0.1"]}]}}]
    })
}

/// The client a `vless://` link builds: `fm` becomes the outbound's `streamSettings.finalmask`
/// as it is (v2rayN `BaseFmt` / `V2rayOutboundService`); no `fm`, no finalmask.
fn vless_client_config(tunnel_port: u16, echo_port: u16, server_port: u16, network: &str, fm: Option<&Value>) -> Value {
    let mut stream = json!({"network": network, "security": "none"});
    if let Some(fm) = fm {
        stream["finalmask"] = fm.clone();
    }
    json!({
        "log": {"loglevel": "warning", "access": "none"},
        "inbounds": [{
            "listen": "127.0.0.1",
            "port": tunnel_port,
            "protocol": "tunnel",
            "settings": {"address": "127.0.0.1", "port": echo_port, "network": "tcp"}
        }],
        "outbounds": [{
            "protocol": "vless",
            "settings": {"address": "127.0.0.1", "port": server_port, "id": VLESS_ID, "encryption": "none"},
            "streamSettings": stream
        }]
    })
}

/// Roadmap §2.6 stage 6.1: the `fm` of a `vless://` link ([`client_finalmask`] of the chain the
/// transport uses) must connect to the server it was built from — with one-sided layers dropped
/// and the unused chain left out. The control (a masked server, a client without `fm`) shows
/// that the masks are really in play.
#[test]
fn vless_share_fm_matches_the_core() {
    let Some(xray) = local_xray_bin() else {
        eprintln!("no local Xray (XRAY_BIN / xray-bin) — skipping the VLESS fm interop check");
        return;
    };
    let dir: PathBuf = std::env::temp_dir().join(format!("feldjaeger-fm-interop-{}", std::process::id()));
    std::fs::create_dir_all(&dir).expect("interop temp dir");
    let echo_port = spawn_echo_server();

    let fragment = json!({"type": "fragment", "settings": {"packets": "1-1", "length": "3-6", "delay": "0"}});
    let sudoku = json!({"type": "sudoku", "settings": {"password": "interop-sudoku"}});
    let header = json!({"type": "header-custom", "settings": {
        "clients": [[{"rand": 8}]], "servers": [[{"rand": 8}]]
    }});
    let mkcp = json!({"type": "mkcp-legacy", "settings": {"value": "interop-seed"}});
    let salamander = json!({"type": "salamander", "settings": {"password": "interop-obfs"}});

    // (label, network, the client dials through, server finalmask, client gets `fm`)
    let cases: Vec<(&str, &str, FinalMaskChain, Value, bool)> = vec![
        ("raw: fragment then sudoku", "raw", FinalMaskChain::Tcp,
            json!({"tcp": [fragment.clone(), sudoku.clone()], "udp": [salamander.clone()]}), true),
        ("raw: header-custom", "raw", FinalMaskChain::Tcp, json!({"tcp": [header]}), true),
        ("kcp: mkcp-legacy then noise", "kcp", FinalMaskChain::Udp,
            json!({"udp": [mkcp.clone(), noise()], "tcp": [sudoku.clone()]}), true),
        ("control: raw sudoku, client without fm", "raw", FinalMaskChain::Tcp, json!({"tcp": [sudoku]}), false),
        ("control: kcp mkcp-legacy, client without fm", "kcp", FinalMaskChain::Udp, json!({"udp": [mkcp]}), false),
    ];

    let failures: Vec<String> = std::thread::scope(|scope| {
        let handles: Vec<_> = cases
            .iter()
            .map(|(label, network, chain, server_fm, with_fm)| {
                let (xray, dir) = (&xray, &dir);
                scope.spawn(move || {
                    let layers = server_fm
                        .get(chain.key())
                        .and_then(Value::as_array)
                        .and_then(|array| parse_finalmask_layers(array))
                        .expect("typed layers");
                    let fm = with_fm
                        .then(|| client_finalmask(&[(*chain, layers.as_slice())]))
                        .flatten()
                        .map(|client| client.value);
                    let server_port = if *chain == FinalMaskChain::Udp { free_udp_port() } else { free_tcp_port() };
                    let tunnel_port = free_tcp_port();
                    let server = vless_server_config(server_port, network, server_fm);
                    let client = vless_client_config(tunnel_port, echo_port, server_port, network, fm.as_ref());
                    let echoed = run_echo(xray, dir, label, &server, &client, tunnel_port);
                    (echoed != *with_fm).then(|| {
                        format!(
                            "{label}: expected {}, got {}\n  server finalmask: {server_fm}\n  client fm: {fm:?}",
                            if *with_fm { "an echo" } else { "no echo" },
                            if echoed { "an echo" } else { "none" },
                        )
                    })
                })
            })
            .collect();
        handles.into_iter().filter_map(|handle| handle.join().expect("interop run panicked")).collect()
    });
    let _ = std::fs::remove_dir_all(&dir);
    assert!(failures.is_empty(), "client finalmask disagrees with Xray-core:\n{}", failures.join("\n"));
}
