//! `streamSettings.finalmask.quicParams` — QUIC tuning shared by every QUIC-based transport
//! (Hysteria today; XHTTP with ALPN `h3` and outbounds later, Roadmap §2.6 stages 3.3 and 7).
//!
//! All 17 fields of the core's `QuicParamsConfig` (`infra/conf/transport_finalmask.go`) are
//! typed (Roadmap §2.6 stage 3.1); [`validate_quic_params`] mirrors the `quicParams` block of
//! `StreamConfig.Build()` (`infra/conf/transport_internet.go`).
//!
//! Losslessness: a known key is typed only when its JSON type is the one the core unmarshals
//! (string / bool / non-negative or signed integer). Anything else — `null`, a number where the
//! core wants a string (`brutalUp: 50000000` fails `json.Unmarshal` into `Bandwidth string`), a
//! float or negative value for a `uint64` window — stays in [`QuicParamsDraft::extras`] untouched
//! and written back as is. Non-`null` mistyped values are reported by validation, because the
//! core rejects the whole config for them.

use serde_json::{Map, Value};

use super::{
    FinalMaskLayerDraft, PortListValue, RangeValue, StreamDirection, UdpHopSettings,
    udphop_settings_to_value,
};

/// Documented `congestion` values (the core lower-cases before matching; empty = `brutal`).
pub const QUIC_CONGESTION_MODES: &[&str] = &["reno", "bbr", "brutal", "force-brutal"];

/// Documented `bbrProfile` values (the core lower-cases before matching; empty = `standard`).
pub const QUIC_BBR_PROFILES: &[&str] = &["conservative", "standard", "aggressive"];

/// The smallest non-zero `brutalUp` / `brutalDown` the core accepts, in bytes per second.
pub const QUIC_MIN_BRUTAL_BYTES_PER_SEC: u64 = 65_536;
/// The smallest non-zero receive window the core accepts (all four windows), in bytes.
pub const QUIC_MIN_RECEIVE_WINDOW: u64 = 16_384;
/// `maxIdleTimeout` range in seconds when non-zero.
pub const QUIC_MAX_IDLE_TIMEOUT_RANGE: (i64, i64) = (4, 120);
/// `keepAlivePeriod` range in seconds when non-zero.
pub const QUIC_KEEP_ALIVE_PERIOD_RANGE: (i64, i64) = (2, 60);
/// The smallest non-zero `maxIncomingStreams`.
pub const QUIC_MIN_INCOMING_STREAMS: i64 = 8;

/// `quicParams` keys only a listening QUIC endpoint reads (`hysteria/hub.go`,
/// `splithttp/hub.go`): the stateless-reset key is generated by the listener.
pub const INBOUND_ONLY_QUIC_PARAMS_FIELDS: &[&str] = &["disableStatelessReset"];

/// `quicParams` keys only a dialing QUIC endpoint reads (`hysteria/dialer.go`,
/// `splithttp/dialer.go`): keep-alive pings and the Chrome QUIC fingerprint are client-side.
pub const OUTBOUND_ONLY_QUIC_PARAMS_FIELDS: &[&str] = &["keepAlivePeriod", "disableChromeParrot"];

/// Whether the `quicParams` key `field` has an effect on the given side. `maxIncomingStreams`
/// is shared: the Hysteria dialer ignores it, the XHTTP/3 dialer does not.
pub fn quic_params_field_applies(field: &str, direction: StreamDirection) -> bool {
    match direction {
        StreamDirection::Inbound => !OUTBOUND_ONLY_QUIC_PARAMS_FIELDS.contains(&field),
        StreamDirection::Outbound => !INBOUND_ONLY_QUIC_PARAMS_FIELDS.contains(&field),
    }
}

/// Typed `finalmask.quicParams` — every field of the core's `QuicParamsConfig`.
///
/// Strings are empty and options `None` when the key is absent (or kept in [`Self::extras`]
/// because its JSON type is wrong); `0` / `false` written explicitly on disk stay explicit.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct QuicParamsDraft {
    /// `congestion`: reno | bbr | brutal | force-brutal (empty = brutal, falling back to bbr
    /// without rates).
    pub congestion: String,
    /// `debug`: sets `HYSTERIA_BBR_DEBUG` / `HYSTERIA_BRUTAL_DEBUG` for the whole Xray process.
    pub debug: Option<bool>,
    /// `bbrProfile`: conservative | standard | aggressive (empty = standard).
    pub bbr_profile: String,
    /// `brutalUp` bandwidth string (e.g. `100 mbps`).
    pub brutal_up: String,
    /// `brutalDown` bandwidth string.
    pub brutal_down: String,
    /// `brutalDisableLossCompensation`.
    pub brutal_disable_loss_compensation: Option<bool>,
    /// `initStreamReceiveWindow` in bytes.
    pub init_stream_receive_window: Option<u64>,
    /// `maxStreamReceiveWindow` in bytes.
    pub max_stream_receive_window: Option<u64>,
    /// `initConnectionReceiveWindow` in bytes.
    pub init_connection_receive_window: Option<u64>,
    /// `maxConnectionReceiveWindow` in bytes.
    pub max_connection_receive_window: Option<u64>,
    /// `maxIdleTimeout` in seconds.
    pub max_idle_timeout: Option<i64>,
    /// `keepAlivePeriod` in seconds (client-only).
    pub keep_alive_period: Option<i64>,
    /// `disablePathMTUDiscovery`.
    pub disable_path_mtu_discovery: Option<bool>,
    /// `disableChromeParrot` (client-only).
    pub disable_chrome_parrot: Option<bool>,
    /// `disableGSO`.
    pub disable_gso: Option<bool>,
    /// `maxIncomingStreams`.
    pub max_incoming_streams: Option<i64>,
    /// `disableStatelessReset` (server-only).
    pub disable_stateless_reset: Option<bool>,
    /// Unknown keys, plus known keys whose JSON type the core would not accept.
    pub extras: Map<String, Value>,
}

/// The JSON type the core unmarshals a `QuicParamsConfig` field into.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FieldKind {
    /// Go `string` / `Bandwidth`.
    Text,
    /// Go `bool`.
    Flag,
    /// Go `uint64`.
    Unsigned,
    /// Go `int64`.
    Signed,
}

impl FieldKind {
    fn accepts(self, value: &Value) -> bool {
        match self {
            Self::Text => value.is_string(),
            Self::Flag => value.is_boolean(),
            Self::Unsigned => value.as_u64().is_some(),
            Self::Signed => value.as_i64().is_some(),
        }
    }

    fn describe(self) -> &'static str {
        match self {
            Self::Text => "a string",
            Self::Flag => "true or false",
            Self::Unsigned => "a non-negative integer",
            Self::Signed => "an integer",
        }
    }
}

/// Every `QuicParamsConfig` JSON key with the type the core expects, in struct order.
const KNOWN_FIELDS: &[(&str, FieldKind)] = &[
    ("congestion", FieldKind::Text),
    ("debug", FieldKind::Flag),
    ("bbrProfile", FieldKind::Text),
    ("brutalUp", FieldKind::Text),
    ("brutalDown", FieldKind::Text),
    ("brutalDisableLossCompensation", FieldKind::Flag),
    ("initStreamReceiveWindow", FieldKind::Unsigned),
    ("maxStreamReceiveWindow", FieldKind::Unsigned),
    ("initConnectionReceiveWindow", FieldKind::Unsigned),
    ("maxConnectionReceiveWindow", FieldKind::Unsigned),
    ("maxIdleTimeout", FieldKind::Signed),
    ("keepAlivePeriod", FieldKind::Signed),
    ("disablePathMTUDiscovery", FieldKind::Flag),
    ("disableChromeParrot", FieldKind::Flag),
    ("disableGSO", FieldKind::Flag),
    ("maxIncomingStreams", FieldKind::Signed),
    ("disableStatelessReset", FieldKind::Flag),
];

fn field_kind(key: &str) -> Option<FieldKind> {
    KNOWN_FIELDS
        .iter()
        .find(|(known, _)| *known == key)
        .map(|(_, kind)| *kind)
}

/// Reads a `quicParams` object. Keys with an unexpected JSON type go to `extras` (module docs).
pub fn parse_quic_params(object: &Map<String, Value>) -> QuicParamsDraft {
    let extras = object
        .iter()
        .filter(|(key, value)| !field_kind(key).is_some_and(|kind| kind.accepts(value)))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    let text = |key: &str| {
        object
            .get(key)
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_owned()
    };
    let flag = |key: &str| object.get(key).and_then(Value::as_bool);
    let unsigned = |key: &str| object.get(key).and_then(Value::as_u64);
    let signed = |key: &str| object.get(key).and_then(Value::as_i64);
    QuicParamsDraft {
        congestion: text("congestion"),
        debug: flag("debug"),
        bbr_profile: text("bbrProfile"),
        brutal_up: text("brutalUp"),
        brutal_down: text("brutalDown"),
        brutal_disable_loss_compensation: flag("brutalDisableLossCompensation"),
        init_stream_receive_window: unsigned("initStreamReceiveWindow"),
        max_stream_receive_window: unsigned("maxStreamReceiveWindow"),
        init_connection_receive_window: unsigned("initConnectionReceiveWindow"),
        max_connection_receive_window: unsigned("maxConnectionReceiveWindow"),
        max_idle_timeout: signed("maxIdleTimeout"),
        keep_alive_period: signed("keepAlivePeriod"),
        disable_path_mtu_discovery: flag("disablePathMTUDiscovery"),
        disable_chrome_parrot: flag("disableChromeParrot"),
        disable_gso: flag("disableGSO"),
        max_incoming_streams: signed("maxIncomingStreams"),
        disable_stateless_reset: flag("disableStatelessReset"),
        extras,
    }
}

/// Serializes the draft: non-empty strings trimmed, set options as JSON bool / number, then
/// extras (a typed value wins over an extra under the same key).
pub fn quic_params_to_value(draft: &QuicParamsDraft) -> Value {
    let mut object = Map::new();
    for (key, value) in [
        ("congestion", &draft.congestion),
        ("bbrProfile", &draft.bbr_profile),
        ("brutalUp", &draft.brutal_up),
        ("brutalDown", &draft.brutal_down),
    ] {
        let value = value.trim();
        if !value.is_empty() {
            object.insert(key.to_owned(), Value::String(value.to_owned()));
        }
    }
    for (key, value) in [
        ("debug", draft.debug),
        ("brutalDisableLossCompensation", draft.brutal_disable_loss_compensation),
        ("disablePathMTUDiscovery", draft.disable_path_mtu_discovery),
        ("disableChromeParrot", draft.disable_chrome_parrot),
        ("disableGSO", draft.disable_gso),
        ("disableStatelessReset", draft.disable_stateless_reset),
    ] {
        if let Some(value) = value {
            object.insert(key.to_owned(), Value::Bool(value));
        }
    }
    for (key, value) in [
        ("initStreamReceiveWindow", draft.init_stream_receive_window),
        ("maxStreamReceiveWindow", draft.max_stream_receive_window),
        ("initConnectionReceiveWindow", draft.init_connection_receive_window),
        ("maxConnectionReceiveWindow", draft.max_connection_receive_window),
    ] {
        if let Some(value) = value {
            object.insert(key.to_owned(), Value::from(value));
        }
    }
    for (key, value) in [
        ("maxIdleTimeout", draft.max_idle_timeout),
        ("keepAlivePeriod", draft.keep_alive_period),
        ("maxIncomingStreams", draft.max_incoming_streams),
    ] {
        if let Some(value) = value {
            object.insert(key.to_owned(), Value::from(value));
        }
    }
    for (key, value) in &draft.extras {
        if !object.contains_key(key) {
            object.insert(key.clone(), value.clone());
        }
    }
    Value::Object(object)
}

impl QuicParamsDraft {
    /// Known keys held in `extras` with a non-`null` value of a type the core rejects and not
    /// overridden by a typed value — written back unchanged, so Save would fail on them.
    pub fn mistyped_keys(&self) -> Vec<&str> {
        let typed = quic_params_to_value(&Self {
            extras: Map::new(),
            ..self.clone()
        });
        self.extras
            .iter()
            .filter(|(key, value)| {
                !value.is_null()
                    && field_kind(key).is_some_and(|kind| !kind.accepts(value))
                    && typed.get(key.as_str()).is_none()
            })
            .map(|(key, _)| key.as_str())
            .collect()
    }

    /// Drops the [`Self::mistyped_keys`] from `extras`; returns true when any was removed.
    pub fn remove_mistyped(&mut self) -> bool {
        let keys: Vec<String> = self.mistyped_keys().into_iter().map(str::to_owned).collect();
        for key in &keys {
            self.extras.remove(key);
        }
        !keys.is_empty()
    }
}

// ─── QUIC transports (Roadmap §2.6 stage 3.3) ───────────────────────────────
//
// Two transports read `quicParams`: Hysteria, and XHTTP when it runs over HTTP/3 — the listener
// (`splithttp/hub.go`: `isH3`) and the dialer (`decideHTTPVersion`) both require TLS with ALPN
// exactly `["h3"]`. On XHTTP/3 the congestion switch (`QListener.Accept`, dialer) knows only
// reno, bbr (also for an empty value) and force-brutal: `brutal` passes `Build()` and then
// panics on every connection. Hysteria's handshake (`CCRX` header) is what carries
// `brutalDown`, so XHTTP/3 does not read it.

/// A transport that reads `finalmask.quicParams`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QuicTransport {
    /// `network: hysteria`.
    Hysteria,
    /// `network: xhttp` / `splithttp` with `security: tls` and `tlsSettings.alpn` exactly `["h3"]`.
    XhttpH3,
}

/// `congestion` values XHTTP/3 accepts (empty = bbr).
pub const XHTTP3_CONGESTION_MODES: &[&str] = &["reno", "bbr", "force-brutal"];

impl QuicTransport {
    /// Name for UI text.
    pub fn label(self) -> &'static str {
        match self {
            Self::Hysteria => "Hysteria",
            Self::XhttpH3 => "XHTTP/3",
        }
    }

    /// The `congestion` values this transport handles.
    pub fn congestion_modes(self) -> &'static [&'static str] {
        match self {
            Self::Hysteria => QUIC_CONGESTION_MODES,
            Self::XhttpH3 => XHTTP3_CONGESTION_MODES,
        }
    }

    /// What an empty `congestion` means on this transport.
    pub fn default_congestion(self) -> &'static str {
        match self {
            Self::Hysteria => "brutal",
            Self::XhttpH3 => "bbr",
        }
    }

    /// Whether the transport reads the `quicParams` key `field` (only `brutalDown` differs).
    pub fn reads_field(self, field: &str) -> bool {
        !(self == Self::XhttpH3 && field == "brutalDown")
    }
}

/// Whether a TLS ALPN list makes XHTTP run over HTTP/3: exactly one entry, `h3` (case-sensitive,
/// untrimmed — compared as the core compares it).
pub fn alpn_selects_http3(alpn: &[String]) -> bool {
    matches!(alpn, [only] if only == "h3")
}

/// The core's `StringList`: an array of strings, or one string split at `,` (not trimmed).
fn string_list(value: Option<&Value>) -> Option<Vec<String>> {
    match value? {
        Value::Array(items) => items.iter().map(|item| item.as_str().map(str::to_owned)).collect(),
        Value::String(text) => Some(text.split(',').map(str::to_owned).collect()),
        _ => None,
    }
}

/// The QUIC transport a `streamSettings` object configures, if any (`network` or the newer
/// `method` key; `security` and the method name compared case-insensitively, as elsewhere).
pub fn quic_transport_of(stream_settings: &Value) -> Option<QuicTransport> {
    let text = |key: &str| {
        stream_settings
            .get(key)
            .and_then(Value::as_str)
            .map(|value| value.trim().to_ascii_lowercase())
    };
    let method = text("network").or_else(|| text("method")).unwrap_or_default();
    match method.as_str() {
        "hysteria" => Some(QuicTransport::Hysteria),
        "xhttp" | "splithttp" => {
            let tls = text("security").as_deref() == Some("tls");
            let alpn = stream_settings
                .get("tlsSettings")
                .and_then(|tls_settings| string_list(tls_settings.get("alpn")))
                .unwrap_or_default();
            (tls && alpn_selects_http3(&alpn)).then_some(QuicTransport::XhttpH3)
        }
        _ => None,
    }
}

/// [`validate_quic_params`] plus what only `transport` refuses: `brutal` on XHTTP/3.
pub fn validate_quic_params_for_transport(
    draft: &QuicParamsDraft,
    transport: QuicTransport,
) -> Result<(), String> {
    validate_quic_params(draft)?;
    let congestion = draft.congestion.trim().to_lowercase();
    if !congestion.is_empty() && !transport.congestion_modes().contains(&congestion.as_str()) {
        return Err(format!(
            "quicParams.congestion \"{}\" is not supported on {} (valid: {}); Xray-core accepts the \
             config but fails every connection",
            draft.congestion.trim(),
            transport.label(),
            transport.congestion_modes().join(", ")
        ));
    }
    Ok(())
}

/// Save-time check of a composed `streamSettings`: the transport-specific rules of
/// [`validate_quic_params_for_transport`] for a `finalmask.quicParams` object on a QUIC
/// transport. Transport-independent rules run where the draft is written (`apply_inbound_stream`).
pub fn validate_stream_quic_params(stream_settings: &Value) -> Result<(), String> {
    let Some(transport) = quic_transport_of(stream_settings) else {
        return Ok(());
    };
    let Some(object) = stream_settings
        .get("finalmask")
        .and_then(|finalmask| finalmask.get("quicParams"))
        .and_then(Value::as_object)
    else {
        return Ok(());
    };
    validate_quic_params_for_transport(&parse_quic_params(object), transport)
        .map_err(|message| format!("streamSettings.finalmask.{message}"))
}

// ─── legacy `udpHop` (Roadmap §2.6 stage 3.2) ───────────────────────────────
//
// Before XTLS/Xray-core#6327 (v26.9.9) port hopping was `quicParams.udpHop {ports, interval}`,
// read only by the Hysteria dialer: it dialed a random port from `ports`, then every `interval`
// seconds (default 30, minimum 5) opened a fresh local socket to another random port of the list.
// That is exactly the `udphop` mask with `intervalLocal,intervalRemote` and
// `remotePorts = ports`. Without `ports` the old dialer did not hop at all. A listener never read
// `udpHop`, on any core.

/// The `quicParams` key removed by XTLS/Xray-core#6327.
pub const QUIC_PARAMS_LEGACY_UDP_HOP_KEY: &str = "udpHop";

/// `udphop.mode` equivalent to the legacy `udpHop` behaviour.
pub const LEGACY_UDP_HOP_MODE: &str = "intervalLocal,intervalRemote";

/// `finalmask.udp[]` types that take over dialing (`HandleDial()` in the core). The core accepts
/// such a mask only at `udp[0]` (`FinalMask.DialUDP`: "incorrect index"), so at most one per chain.
pub const DIAL_HANDLING_UDP_FINALMASK_TYPES: &[&str] = &["udphop", "xicmp"];

/// What [`migrate_legacy_udp_hop`] did.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LegacyUdpHopMigration {
    /// Inbound: a listener never read `udpHop`; the key was removed.
    RemovedServerSide,
    /// Outbound without `ports` (or `udpHop: null`): the old dialer did not hop; the key was removed.
    RemovedInactive,
    /// Outbound: a `udphop` layer was inserted at `finalmask.udp[0]` and the key removed.
    /// `dropped_keys` — keys of the old object other than `ports`/`interval` (never read by any
    /// core), not carried over.
    Migrated { dropped_keys: Vec<String> },
}

impl QuicParamsDraft {
    /// `true` while the removed `quicParams.udpHop` is still in the draft.
    pub fn has_legacy_udp_hop(&self) -> bool {
        self.extras.contains_key(QUIC_PARAMS_LEGACY_UDP_HOP_KEY)
    }

    /// Drops `quicParams.udpHop`; returns true when it was there.
    pub fn remove_legacy_udp_hop(&mut self) -> bool {
        self.extras.remove(QUIC_PARAMS_LEGACY_UDP_HOP_KEY).is_some()
    }
}

/// The `udphop` layer equivalent to a legacy `udpHop` value; `Ok(None)` when the old dialer would
/// not have hopped (no `ports`, or `null`). `ports` and `interval` are carried over in their JSON
/// shape. Fails on a shape the old core could not unmarshal either.
pub fn udphop_layer_from_legacy_udp_hop(
    legacy: &Value,
) -> Result<Option<(FinalMaskLayerDraft, Vec<String>)>, String> {
    let object = match legacy {
        Value::Null => return Ok(None),
        Value::Object(object) => object,
        other => return Err(format!("quicParams.udpHop must be an object (got {other})")),
    };
    let remote_ports = PortListValue::parse(object.get("ports"))
        .ok_or_else(|| "quicParams.udpHop.ports must be a port number or a port list string".to_owned())?;
    let interval = RangeValue::parse(object.get("interval"))
        .ok_or_else(|| "quicParams.udpHop.interval must be a number or a \"FROM-TO\" string".to_owned())?;
    if remote_ports.text.trim().is_empty() {
        return Ok(None);
    }
    let settings = UdpHopSettings {
        mode: LEGACY_UDP_HOP_MODE.to_owned(),
        interval,
        remote_ports,
        remote_ips: Vec::new(),
        extras: Map::new(),
    };
    let dropped_keys = object
        .keys()
        .filter(|key| !matches!(key.as_str(), "ports" | "interval"))
        .cloned()
        .collect();
    Ok(Some((
        FinalMaskLayerDraft {
            layer_type: "udphop".to_owned(),
            settings: udphop_settings_to_value(&settings),
        },
        dropped_keys,
    )))
}

/// Migrates `quicParams.udpHop` (an explicit user action). Inbound: removes the key (it never had
/// an effect on a listener — turning it into a client-only `udphop` layer would break the
/// listener). Outbound: inserts the equivalent `udphop` layer at `udp[0]` and removes the key.
/// On error nothing is changed.
pub fn migrate_legacy_udp_hop(
    quic_params: &mut QuicParamsDraft,
    udp_layers: &mut Vec<FinalMaskLayerDraft>,
    direction: StreamDirection,
) -> Result<LegacyUdpHopMigration, String> {
    let legacy = quic_params
        .extras
        .get(QUIC_PARAMS_LEGACY_UDP_HOP_KEY)
        .ok_or_else(|| "quicParams has no udpHop".to_owned())?;
    if direction == StreamDirection::Inbound {
        quic_params.remove_legacy_udp_hop();
        return Ok(LegacyUdpHopMigration::RemovedServerSide);
    }
    let Some((layer, dropped_keys)) = udphop_layer_from_legacy_udp_hop(legacy)? else {
        quic_params.remove_legacy_udp_hop();
        return Ok(LegacyUdpHopMigration::RemovedInactive);
    };
    for (index, existing) in udp_layers.iter().enumerate() {
        let existing_type = existing.layer_type.trim().to_ascii_lowercase();
        if DIAL_HANDLING_UDP_FINALMASK_TYPES.contains(&existing_type.as_str()) {
            return Err(format!(
                "finalmask.udp[{index}] is already a `{existing_type}` layer; Xray-core allows only \
                 one dial-handling mask (udphop, xicmp), at udp[0] — remove udpHop or that layer"
            ));
        }
    }
    udp_layers.insert(0, layer);
    quic_params.remove_legacy_udp_hop();
    Ok(LegacyUdpHopMigration::Migrated { dropped_keys })
}

/// `Bandwidth.Bps()` of the core (`infra/conf/transport_method.go`): a decimal number and an
/// optional unit — `b`/`bps`, `k`/`kb`/`kbps`, `m`/…, `g`/…, `t`/… (case-insensitive, powers of
/// 1024) — read as **bits** per second and returned as bytes per second. Empty is `0`.
///
/// The number ends at the first character that is neither a digit nor `.`, so `1e6`, `-5` or
/// `mbps` alone are errors, exactly as in the core.
pub fn quic_bandwidth_bytes_per_sec(text: &str) -> Result<u64, String> {
    let text = text.trim().to_lowercase();
    if text.is_empty() {
        return Ok(0);
    }
    let split = text
        .find(|c: char| !c.is_ascii_digit() && c != '.')
        .unwrap_or(text.len());
    let (number, unit) = text.split_at(split);
    let number: f64 = number
        .parse()
        .map_err(|_| format!("\"{text}\" does not start with a number"))?;
    let multiplier: u64 = match unit.trim() {
        "" | "b" | "bps" => 1,
        "k" | "kb" | "kbps" => 1 << 10,
        "m" | "mb" | "mbps" => 1 << 20,
        "g" | "gb" | "gbps" => 1 << 30,
        "t" | "tb" | "tbps" => 1 << 40,
        other => return Err(format!("unsupported unit \"{other}\" (use bps, kbps, mbps, gbps or tbps)")),
    };
    // `uint64(val*float64(mul)) / 8` — the float-to-integer cast saturates in Rust.
    Ok((number * multiplier as f64) as u64 / 8)
}

/// Mirrors the `quicParams` checks of `StreamConfig.Build()`, in the same order, on the values
/// [`quic_params_to_value`] would write. Fails first on known keys the core cannot unmarshal.
pub fn validate_quic_params(draft: &QuicParamsDraft) -> Result<(), String> {
    if let Some(key) = draft.mistyped_keys().first() {
        let kind = field_kind(key).map_or("", FieldKind::describe);
        return Err(format!(
            "quicParams.{key} must be {kind} (got {})",
            draft.extras.get(*key).unwrap_or(&Value::Null)
        ));
    }

    let profile = draft.bbr_profile.trim().to_lowercase();
    if !profile.is_empty() && !QUIC_BBR_PROFILES.contains(&profile.as_str()) {
        return Err(format!(
            "quicParams.bbrProfile: unknown profile \"{}\" (valid: {})",
            draft.bbr_profile.trim(),
            QUIC_BBR_PROFILES.join(", ")
        ));
    }

    let up = quic_bandwidth_bytes_per_sec(&draft.brutal_up)
        .map_err(|error| format!("quicParams.brutalUp: {error}"))?;
    let down = quic_bandwidth_bytes_per_sec(&draft.brutal_down)
        .map_err(|error| format!("quicParams.brutalDown: {error}"))?;
    for (key, bytes) in [("brutalUp", up), ("brutalDown", down)] {
        if bytes > 0 && bytes < QUIC_MIN_BRUTAL_BYTES_PER_SEC {
            return Err(format!(
                "quicParams.{key} must be at least {QUIC_MIN_BRUTAL_BYTES_PER_SEC} bytes per second \
                 (512 kbps); got {bytes}"
            ));
        }
    }

    let congestion = draft.congestion.trim().to_lowercase();
    match congestion.as_str() {
        "" | "brutal" | "reno" | "bbr" => {}
        "force-brutal" if up == 0 => {
            return Err("quicParams.congestion force-brutal requires brutalUp".to_owned());
        }
        "force-brutal" => {}
        _ => {
            return Err(format!(
                "quicParams.congestion: unknown value \"{}\" (valid: {})",
                draft.congestion.trim(),
                QUIC_CONGESTION_MODES.join(", ")
            ));
        }
    }

    for (key, window) in [
        ("initStreamReceiveWindow", draft.init_stream_receive_window),
        ("maxStreamReceiveWindow", draft.max_stream_receive_window),
        ("initConnectionReceiveWindow", draft.init_connection_receive_window),
        ("maxConnectionReceiveWindow", draft.max_connection_receive_window),
    ] {
        if let Some(window) = window
            && window > 0
            && window < QUIC_MIN_RECEIVE_WINDOW
        {
            return Err(format!(
                "quicParams.{key} must be at least {QUIC_MIN_RECEIVE_WINDOW} (got {window})"
            ));
        }
    }
    for (key, value, (min, max)) in [
        ("maxIdleTimeout", draft.max_idle_timeout, QUIC_MAX_IDLE_TIMEOUT_RANGE),
        ("keepAlivePeriod", draft.keep_alive_period, QUIC_KEEP_ALIVE_PERIOD_RANGE),
    ] {
        if let Some(value) = value
            && value != 0
            && !(min..=max).contains(&value)
        {
            return Err(format!(
                "quicParams.{key} must be between {min} and {max} seconds, or 0 for the default (got {value})"
            ));
        }
    }
    if let Some(streams) = draft.max_incoming_streams
        && streams != 0
        && streams < QUIC_MIN_INCOMING_STREAMS
    {
        return Err(format!(
            "quicParams.maxIncomingStreams must be at least {QUIC_MIN_INCOMING_STREAMS}, or 0 for the default (got {streams})"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn parse(value: Value) -> QuicParamsDraft {
        parse_quic_params(value.as_object().expect("object"))
    }

    #[test]
    fn roundtrip_keeps_all_seventeen_fields_and_extras() {
        let value = json!({
            "congestion": "brutal", "debug": false, "bbrProfile": "aggressive",
            "brutalUp": "100 mbps", "brutalDown": "1 gbps", "brutalDisableLossCompensation": true,
            "initStreamReceiveWindow": 8_388_608, "maxStreamReceiveWindow": 8_388_608,
            "initConnectionReceiveWindow": 20_971_520, "maxConnectionReceiveWindow": 0,
            "maxIdleTimeout": 30, "keepAlivePeriod": 0, "disablePathMTUDiscovery": false,
            "disableChromeParrot": true, "disableGSO": true, "maxIncomingStreams": 1024,
            "disableStatelessReset": false, "futureKey": [1]
        });
        let draft = parse(value.clone());
        assert_eq!(draft.bbr_profile, "aggressive");
        assert_eq!(draft.debug, Some(false));
        assert_eq!(draft.max_connection_receive_window, Some(0));
        assert_eq!(draft.max_incoming_streams, Some(1024));
        assert_eq!(draft.extras.keys().collect::<Vec<_>>(), vec!["futureKey"]);
        assert_eq!(quic_params_to_value(&draft), value);
        assert_eq!(KNOWN_FIELDS.len(), 17);
    }

    #[test]
    fn mistyped_and_null_values_stay_in_extras_unchanged() {
        // A number for a Bandwidth string, a negative / float window and null all fail or are
        // no-ops in Go's json.Unmarshal — they are never "fixed" silently.
        let value = json!({
            "brutalDown": 50_000_000, "initStreamReceiveWindow": -1,
            "maxStreamReceiveWindow": 16_384.0, "debug": null, "maxIdleTimeout": "30"
        });
        let draft = parse(value.clone());
        assert_eq!(draft.brutal_down, "");
        assert_eq!(draft.init_stream_receive_window, None);
        assert_eq!(draft.extras.len(), 5);
        assert_eq!(quic_params_to_value(&draft), value);
        let mut keys = draft.mistyped_keys();
        keys.sort_unstable();
        assert_eq!(
            keys,
            vec!["brutalDown", "initStreamReceiveWindow", "maxIdleTimeout", "maxStreamReceiveWindow"]
        );
        assert_eq!(
            validate_quic_params(&draft).unwrap_err(),
            "quicParams.brutalDown must be a string (got 50000000)"
        );
    }

    #[test]
    fn a_typed_value_overrides_and_remove_mistyped_drops_extras() {
        let mut draft = parse(json!({"brutalUp": 1, "debug": null, "x": 1}));
        draft.brutal_up = "200 mbps".to_owned();
        assert!(draft.mistyped_keys().is_empty());
        assert_eq!(quic_params_to_value(&draft), json!({"brutalUp": "200 mbps", "debug": null, "x": 1}));

        draft.brutal_up.clear();
        assert!(draft.remove_mistyped());
        assert!(!draft.remove_mistyped());
        assert_eq!(quic_params_to_value(&draft), json!({"debug": null, "x": 1}));
    }

    #[test]
    fn blank_strings_are_omitted_and_written_trimmed() {
        let draft = QuicParamsDraft {
            congestion: "  ".to_owned(),
            bbr_profile: " standard ".to_owned(),
            ..QuicParamsDraft::default()
        };
        assert_eq!(quic_params_to_value(&draft), json!({"bbrProfile": "standard"}));
    }

    #[test]
    fn bandwidth_matches_core_bps() {
        let cases: &[(&str, u64)] = &[
            ("", 0),
            ("  ", 0),
            ("800", 100),
            ("8 bps", 1),
            ("100 mbps", 100 * 1_048_576 / 8),
            ("100MBPS", 100 * 1_048_576 / 8),
            ("1.5 g", (1.5 * 1_073_741_824.0) as u64 / 8),
            ("512 kbps", 65_536),
            ("1 t", 1_099_511_627_776 / 8),
            (".5m", 65_536),
            ("5.", 0),
        ];
        for (text, bytes) in cases {
            assert_eq!(quic_bandwidth_bytes_per_sec(text), Ok(*bytes), "{text:?}");
        }
        for text in ["mbps", "-5 mbps", "1e6", "1.2.3", "10 mib", "10 m b"] {
            assert!(quic_bandwidth_bytes_per_sec(text).is_err(), "{text:?}");
        }
    }

    #[test]
    fn validation_mirrors_core_build() {
        let ok = [
            json!({}),
            json!({"congestion": "BBR", "bbrProfile": "Conservative"}),
            json!({"congestion": "force-brutal", "brutalUp": "512 kbps"}),
            json!({"brutalUp": "0", "brutalDown": "0 mbps"}),
            json!({"initStreamReceiveWindow": 0, "maxConnectionReceiveWindow": 16_384}),
            json!({"maxIdleTimeout": 0, "keepAlivePeriod": 60, "maxIncomingStreams": 0}),
            json!({"maxIdleTimeout": 4}),
            json!({"maxIdleTimeout": 120, "keepAlivePeriod": 2, "maxIncomingStreams": 8}),
        ];
        for value in ok {
            assert_eq!(validate_quic_params(&parse(value.clone())), Ok(()), "{value}");
        }
        let bad = [
            (json!({"congestion": "cubic"}), "unknown value \"cubic\""),
            (json!({"bbrProfile": "turbo"}), "unknown profile \"turbo\""),
            (json!({"congestion": "force-brutal"}), "force-brutal requires brutalUp"),
            (json!({"congestion": "force-brutal", "brutalUp": "0"}), "force-brutal requires brutalUp"),
            (json!({"brutalUp": "511 kbps"}), "brutalUp must be at least 65536"),
            (json!({"brutalDown": "100 bps"}), "brutalDown must be at least 65536"),
            (json!({"brutalUp": "fast"}), "brutalUp: \"fast\" does not start with a number"),
            (json!({"brutalDown": "10 mib"}), "brutalDown: unsupported unit \"mib\""),
            (json!({"maxStreamReceiveWindow": 16_383}), "maxStreamReceiveWindow must be at least 16384"),
            (json!({"initConnectionReceiveWindow": 1}), "initConnectionReceiveWindow must be at least"),
            (json!({"maxIdleTimeout": 3}), "maxIdleTimeout must be between 4 and 120"),
            (json!({"maxIdleTimeout": -1}), "maxIdleTimeout must be between 4 and 120"),
            (json!({"keepAlivePeriod": 61}), "keepAlivePeriod must be between 2 and 60"),
            (json!({"maxIncomingStreams": 7}), "maxIncomingStreams must be at least 8"),
            (json!({"maxIncomingStreams": -8}), "maxIncomingStreams must be at least 8"),
            (json!({"disableGSO": "yes"}), "disableGSO must be true or false"),
        ];
        for (value, needle) in bad {
            let error = validate_quic_params(&parse(value.clone())).expect_err(&value.to_string());
            assert!(error.contains(needle), "{value}: {error}");
        }
    }

    #[test]
    fn quic_transport_follows_method_security_and_exact_h3_alpn() {
        let xhttp = |security: &str, alpn: Value| {
            json!({"network": "xhttp", "security": security, "tlsSettings": {"alpn": alpn}})
        };
        let cases = [
            (json!({"network": "hysteria"}), Some(QuicTransport::Hysteria)),
            (json!({"method": " Hysteria "}), Some(QuicTransport::Hysteria)),
            (xhttp("tls", json!(["h3"])), Some(QuicTransport::XhttpH3)),
            (xhttp("TLS", json!("h3")), Some(QuicTransport::XhttpH3)),
            (json!({"network": "splithttp", "security": "tls", "tlsSettings": {"alpn": ["h3"]}}), Some(QuicTransport::XhttpH3)),
            (json!({"method": "xhttp", "security": "tls", "tlsSettings": {"alpn": "h3"}}), Some(QuicTransport::XhttpH3)),
            // Exactly one entry, compared as the core does: no trim, case-sensitive.
            (xhttp("tls", json!(["h3", "h2"])), None),
            (xhttp("tls", json!("h3,h2")), None),
            (xhttp("tls", json!([" h3"])), None),
            (xhttp("tls", json!(["H3"])), None),
            (xhttp("tls", json!([])), None),
            (json!({"network": "xhttp", "security": "tls"}), None),
            (xhttp("reality", json!(["h3"])), None),
            (xhttp("none", json!(["h3"])), None),
            (json!({"network": "tcp", "security": "tls", "tlsSettings": {"alpn": ["h3"]}}), None),
            (json!({}), None),
        ];
        for (stream, expected) in cases {
            assert_eq!(quic_transport_of(&stream), expected, "{stream}");
        }
        assert!(alpn_selects_http3(&["h3".to_owned()]));
        assert!(!alpn_selects_http3(&[]));
    }

    #[test]
    fn xhttp3_refuses_brutal_and_does_not_read_brutal_down() {
        let draft = |congestion: &str| QuicParamsDraft {
            congestion: congestion.to_owned(),
            brutal_up: "100 mbps".to_owned(),
            ..QuicParamsDraft::default()
        };
        for ok in ["", "reno", "BBR", "force-brutal"] {
            assert_eq!(validate_quic_params_for_transport(&draft(ok), QuicTransport::XhttpH3), Ok(()), "{ok}");
        }
        for congestion in ["brutal", "Brutal"] {
            let error = validate_quic_params_for_transport(&draft(congestion), QuicTransport::XhttpH3).unwrap_err();
            assert!(error.contains("is not supported on XHTTP/3 (valid: reno, bbr, force-brutal)"), "{error}");
            assert_eq!(validate_quic_params_for_transport(&draft(congestion), QuicTransport::Hysteria), Ok(()));
        }
        // Transport-independent rules still apply first.
        let error = validate_quic_params_for_transport(&draft("cubic"), QuicTransport::XhttpH3).unwrap_err();
        assert!(error.contains("unknown value \"cubic\""), "{error}");

        assert_eq!(QuicTransport::Hysteria.default_congestion(), "brutal");
        assert_eq!(QuicTransport::XhttpH3.default_congestion(), "bbr");
        assert!(!QuicTransport::XhttpH3.reads_field("brutalDown"));
        assert!(QuicTransport::XhttpH3.reads_field("brutalUp"));
        assert!(QuicTransport::Hysteria.reads_field("brutalDown"));
    }

    #[test]
    fn stream_check_applies_only_to_quic_params_on_a_quic_transport() {
        let stream = |network: &str, alpn: Value, quic_params: Value| {
            json!({"network": network, "security": "tls", "tlsSettings": {"alpn": alpn},
                   "finalmask": {"quicParams": quic_params}})
        };
        let brutal = json!({"congestion": "brutal"});
        let error = validate_stream_quic_params(&stream("xhttp", json!(["h3"]), brutal.clone())).unwrap_err();
        assert!(error.starts_with("streamSettings.finalmask.quicParams.congestion \"brutal\""), "{error}");
        // XHTTP over TCP never reads quicParams; Hysteria handles brutal.
        assert_eq!(validate_stream_quic_params(&stream("xhttp", json!(["h2"]), brutal.clone())), Ok(()));
        assert_eq!(validate_stream_quic_params(&stream("hysteria", json!(["h3"]), brutal)), Ok(()));
        // No quicParams / a foreign finalmask: nothing to check here.
        assert_eq!(validate_stream_quic_params(&json!({"network": "xhttp", "security": "tls",
            "tlsSettings": {"alpn": ["h3"]}, "finalmask": "x"})), Ok(()));
    }

    fn layer(layer_type: &str) -> FinalMaskLayerDraft {
        FinalMaskLayerDraft {
            layer_type: layer_type.to_owned(),
            settings: json!({}),
        }
    }

    #[test]
    fn legacy_udp_hop_becomes_an_interval_local_remote_layer_in_its_json_shape() {
        let (converted, dropped) =
            udphop_layer_from_legacy_udp_hop(&json!({"ports": "20000-50000", "interval": "10-20", "x": 1}))
                .expect("valid")
                .expect("active");
        assert_eq!(converted.layer_type, "udphop");
        assert_eq!(
            converted.settings,
            json!({"mode": "intervalLocal,intervalRemote", "remotePorts": "20000-50000", "interval": "10-20"})
        );
        assert_eq!(dropped, vec!["x"]);
        // A numeric port / interval stays numeric; an absent interval stays absent (default 30 in
        // both the old dialer and the mask).
        let (converted, _) = udphop_layer_from_legacy_udp_hop(&json!({"ports": 443}))
            .expect("valid")
            .expect("active");
        assert_eq!(converted.settings, json!({"mode": "intervalLocal,intervalRemote", "remotePorts": 443}));
        let (converted, _) = udphop_layer_from_legacy_udp_hop(&json!({"ports": "1000,2000", "interval": 30}))
            .expect("valid")
            .expect("active");
        assert_eq!(converted.settings["interval"], json!(30));
    }

    #[test]
    fn legacy_udp_hop_without_ports_did_not_hop_and_bad_shapes_are_refused() {
        for inactive in [json!(null), json!({}), json!({"interval": 30}), json!({"ports": ""}), json!({"ports": null})] {
            assert_eq!(udphop_layer_from_legacy_udp_hop(&inactive), Ok(None), "{inactive}");
        }
        for (bad, needle) in [
            (json!("20000-50000"), "udpHop must be an object"),
            (json!({"ports": [1, 2]}), "udpHop.ports must be"),
            (json!({"ports": "1-2", "interval": 1.5}), "udpHop.interval must be"),
        ] {
            let error = udphop_layer_from_legacy_udp_hop(&bad).expect_err(&bad.to_string());
            assert!(error.contains(needle), "{bad}: {error}");
        }
    }

    #[test]
    fn migration_follows_direction_and_respects_the_dial_handling_slot() {
        let draft = parse(json!({"congestion": "bbr", "udpHop": {"ports": "20000-50000", "interval": 30}}));
        assert!(draft.has_legacy_udp_hop());

        // Inbound: a listener never read udpHop — removed, the chain untouched.
        let (mut inbound, mut udp) = (draft.clone(), vec![layer("salamander")]);
        assert_eq!(
            migrate_legacy_udp_hop(&mut inbound, &mut udp, StreamDirection::Inbound),
            Ok(LegacyUdpHopMigration::RemovedServerSide)
        );
        assert!(!inbound.has_legacy_udp_hop());
        assert_eq!(udp, vec![layer("salamander")]);
        assert_eq!(quic_params_to_value(&inbound), json!({"congestion": "bbr"}));

        // Outbound: the layer goes to udp[0], ahead of the other masks.
        let (mut outbound, mut udp) = (draft.clone(), vec![layer("salamander")]);
        assert_eq!(
            migrate_legacy_udp_hop(&mut outbound, &mut udp, StreamDirection::Outbound),
            Ok(LegacyUdpHopMigration::Migrated { dropped_keys: Vec::new() })
        );
        assert!(!outbound.has_legacy_udp_hop());
        assert_eq!(udp.len(), 2);
        assert_eq!(udp[0].layer_type, "udphop");
        assert_eq!(udp[0].settings["remotePorts"], "20000-50000");
        assert_eq!(udp[1], layer("salamander"));

        // Outbound with another dial-handling mask anywhere: refused, nothing changed.
        for existing in ["udphop", " XICMP "] {
            let (mut outbound, mut udp) = (draft.clone(), vec![layer("noise"), layer(existing)]);
            let error = migrate_legacy_udp_hop(&mut outbound, &mut udp, StreamDirection::Outbound).unwrap_err();
            assert!(error.contains("finalmask.udp[1] is already a"), "{error}");
            assert!(outbound.has_legacy_udp_hop());
            assert_eq!(udp.len(), 2);
        }

        // Outbound without ports: the old dialer did not hop — removed, no layer.
        let mut inactive = parse(json!({"udpHop": {"interval": 30}}));
        let mut udp = Vec::new();
        assert_eq!(
            migrate_legacy_udp_hop(&mut inactive, &mut udp, StreamDirection::Outbound),
            Ok(LegacyUdpHopMigration::RemovedInactive)
        );
        assert!(udp.is_empty() && !inactive.has_legacy_udp_hop());

        // A broken shape is refused on an outbound, removed on an inbound (it is dead there).
        let broken = parse(json!({"udpHop": "20000-50000"}));
        assert!(migrate_legacy_udp_hop(&mut broken.clone(), &mut Vec::new(), StreamDirection::Outbound).is_err());
        assert_eq!(
            migrate_legacy_udp_hop(&mut broken.clone(), &mut Vec::new(), StreamDirection::Inbound),
            Ok(LegacyUdpHopMigration::RemovedServerSide)
        );
        assert!(migrate_legacy_udp_hop(&mut QuicParamsDraft::default(), &mut Vec::new(), StreamDirection::Inbound).is_err());
    }

    #[test]
    fn field_applicability_follows_direction() {
        use StreamDirection::{Inbound, Outbound};
        assert!(quic_params_field_applies("disableStatelessReset", Inbound));
        assert!(!quic_params_field_applies("disableStatelessReset", Outbound));
        for field in OUTBOUND_ONLY_QUIC_PARAMS_FIELDS {
            assert!(!quic_params_field_applies(field, Inbound));
            assert!(quic_params_field_applies(field, Outbound));
        }
        for (field, _) in KNOWN_FIELDS {
            assert!(
                quic_params_field_applies(field, Inbound) || quic_params_field_applies(field, Outbound),
                "{field} applies nowhere"
            );
        }
        assert!(quic_params_field_applies("maxIncomingStreams", Outbound));
        assert!(quic_params_field_applies("someFutureKey", Inbound));
    }
}
